version: "3.1"
services:
  test-app:
    container_name: test-app
    image: test-app
    build:
      context: .
      dockerfile: Dockerfile.yml
    environment: 
      - APP_MESSAGE=Hello, Python App!
    ports:
      - "80:5000"